// Auto-generated from superdoc package - DO NOT EDIT
// Run: npx tsx scripts/generate-operations.ts > server/operations.ts

export const OPERATIONS = [
  'authorities.configure',
  'authorities.entries.get',
  'authorities.entries.insert',
  'authorities.entries.list',
  'authorities.entries.remove',
  'authorities.entries.update',
  'authorities.get',
  'authorities.insert',
  'authorities.list',
  'authorities.rebuild',
  'authorities.remove',
  'blocks.delete',
  'blocks.deleteRange',
  'blocks.list',
  'bookmarks.get',
  'bookmarks.insert',
  'bookmarks.list',
  'bookmarks.remove',
  'bookmarks.rename',
  'capabilities.get',
  'captions.configure',
  'captions.get',
  'captions.insert',
  'captions.list',
  'captions.remove',
  'captions.update',
  'citations.bibliography.configure',
  'citations.bibliography.get',
  'citations.bibliography.insert',
  'citations.bibliography.rebuild',
  'citations.bibliography.remove',
  'citations.get',
  'citations.insert',
  'citations.list',
  'citations.remove',
  'citations.sources.get',
  'citations.sources.insert',
  'citations.sources.list',
  'citations.sources.remove',
  'citations.sources.update',
  'citations.update',
  'comments.create',
  'comments.delete',
  'comments.get',
  'comments.list',
  'comments.patch',
  'contentControls.appendContent',
  'contentControls.checkbox.getState',
  'contentControls.checkbox.setState',
  'contentControls.checkbox.setSymbolPair',
  'contentControls.checkbox.toggle',
  'contentControls.choiceList.getItems',
  'contentControls.choiceList.setItems',
  'contentControls.choiceList.setSelected',
  'contentControls.clearBinding',
  'contentControls.clearContent',
  'contentControls.copy',
  'contentControls.date.clearValue',
  'contentControls.date.setCalendar',
  'contentControls.date.setDisplayFormat',
  'contentControls.date.setDisplayLocale',
  'contentControls.date.setStorageFormat',
  'contentControls.date.setValue',
  'contentControls.delete',
  'contentControls.get',
  'contentControls.getBinding',
  'contentControls.getContent',
  'contentControls.getParent',
  'contentControls.getRawProperties',
  'contentControls.group.ungroup',
  'contentControls.group.wrap',
  'contentControls.insertAfter',
  'contentControls.insertBefore',
  'contentControls.list',
  'contentControls.listChildren',
  'contentControls.listInRange',
  'contentControls.move',
  'contentControls.normalizeTagPayload',
  'contentControls.normalizeWordCompatibility',
  'contentControls.patch',
  'contentControls.patchRawProperties',
  'contentControls.prependContent',
  'contentControls.repeatingSection.cloneItem',
  'contentControls.repeatingSection.deleteItem',
  'contentControls.repeatingSection.insertItemAfter',
  'contentControls.repeatingSection.insertItemBefore',
  'contentControls.repeatingSection.listItems',
  'contentControls.repeatingSection.setAllowInsertDelete',
  'contentControls.replaceContent',
  'contentControls.selectByTag',
  'contentControls.selectByTitle',
  'contentControls.setBinding',
  'contentControls.setLockMode',
  'contentControls.setType',
  'contentControls.text.clearValue',
  'contentControls.text.setMultiline',
  'contentControls.text.setValue',
  'contentControls.unwrap',
  'contentControls.validateWordCompatibility',
  'contentControls.wrap',
  'create.contentControl',
  'create.heading',
  'create.image',
  'create.paragraph',
  'create.sectionBreak',
  'create.table',
  'create.tableOfContents',
  'crossRefs.get',
  'crossRefs.insert',
  'crossRefs.list',
  'crossRefs.rebuild',
  'crossRefs.remove',
  'customXml.parts.create',
  'customXml.parts.list',
  'fields.get',
  'fields.insert',
  'fields.list',
  'fields.rebuild',
  'fields.remove',
  'footnotes.configure',
  'footnotes.get',
  'footnotes.insert',
  'footnotes.list',
  'footnotes.remove',
  'footnotes.update',
  'format.apply',
  'format.paragraph.clearAlignment',
  'format.paragraph.clearAllTabStops',
  'format.paragraph.clearBorder',
  'format.paragraph.clearDirection',
  'format.paragraph.clearIndentation',
  'format.paragraph.clearShading',
  'format.paragraph.clearSpacing',
  'format.paragraph.clearTabStop',
  'format.paragraph.resetDirectFormatting',
  'format.paragraph.setAlignment',
  'format.paragraph.setBorder',
  'format.paragraph.setDirection',
  'format.paragraph.setFlowOptions',
  'format.paragraph.setIndentation',
  'format.paragraph.setKeepOptions',
  'format.paragraph.setOutlineLevel',
  'format.paragraph.setShading',
  'format.paragraph.setSpacing',
  'format.paragraph.setTabStop',
  'headerFooters.get',
  'headerFooters.list',
  'headerFooters.parts.create',
  'headerFooters.parts.delete',
  'headerFooters.parts.list',
  'headerFooters.refs.clear',
  'headerFooters.refs.set',
  'headerFooters.refs.setLinkedToPrevious',
  'headerFooters.resolve',
  'history.get',
  'history.redo',
  'history.undo',
  'hyperlinks.get',
  'hyperlinks.insert',
  'hyperlinks.list',
  'hyperlinks.patch',
  'hyperlinks.remove',
  'hyperlinks.wrap',
  'images.convertToFloating',
  'images.convertToInline',
  'images.crop',
  'images.delete',
  'images.flip',
  'images.get',
  'images.insertCaption',
  'images.list',
  'images.move',
  'images.removeCaption',
  'images.replaceSource',
  'images.resetCrop',
  'images.rotate',
  'images.scale',
  'images.setAltText',
  'images.setAnchorOptions',
  'images.setDecorative',
  'images.setHyperlink',
  'images.setLockAspectRatio',
  'images.setName',
  'images.setPosition',
  'images.setSize',
  'images.setWrapDistances',
  'images.setWrapSide',
  'images.setWrapType',
  'images.setZOrder',
  'images.updateCaption',
  'index.configure',
  'index.entries.get',
  'index.entries.insert',
  'index.entries.list',
  'index.entries.remove',
  'index.entries.update',
  'index.get',
  'index.insert',
  'index.list',
  'index.rebuild',
  'index.remove',
  'lists.applyPreset',
  'lists.applyStyle',
  'lists.applyTemplate',
  'lists.attach',
  'lists.canContinuePrevious',
  'lists.canJoin',
  'lists.captureTemplate',
  'lists.clearLevelOverrides',
  'lists.continuePrevious',
  'lists.convertToText',
  'lists.create',
  'lists.detach',
  'lists.get',
  'lists.getStyle',
  'lists.indent',
  'lists.insert',
  'lists.join',
  'lists.list',
  'lists.merge',
  'lists.outdent',
  'lists.restartAt',
  'lists.separate',
  'lists.setLevel',
  'lists.setLevelAlignment',
  'lists.setLevelBullet',
  'lists.setLevelIndents',
  'lists.setLevelLayout',
  'lists.setLevelMarkerFont',
  'lists.setLevelNumbering',
  'lists.setLevelNumberStyle',
  'lists.setLevelPictureBullet',
  'lists.setLevelRestart',
  'lists.setLevelStart',
  'lists.setLevelText',
  'lists.setLevelTrailingCharacter',
  'lists.setType',
  'lists.setValue',
  'lists.split',
  'metadata.get',
  'metadata.list',
  'metadata.remove',
  'metadata.resolve',
  'metadata.update',
  'mutations.apply',
  'mutations.preview',
  'permissionRanges.create',
  'permissionRanges.get',
  'permissionRanges.list',
  'permissionRanges.remove',
  'permissionRanges.updatePrincipal',
  'protection.clearEditingRestriction',
  'protection.get',
  'protection.setEditingRestriction',
  'query.match',
  'ranges.resolve',
  'sections.clearHeaderFooterRef',
  'sections.clearPageBorders',
  'sections.get',
  'sections.list',
  'sections.setBreakType',
  'sections.setColumns',
  'sections.setHeaderFooterMargins',
  'sections.setHeaderFooterRef',
  'sections.setLineNumbering',
  'sections.setLinkToPrevious',
  'sections.setOddEvenHeadersFooters',
  'sections.setPageBorders',
  'sections.setPageMargins',
  'sections.setPageNumbering',
  'sections.setPageSetup',
  'sections.setSectionDirection',
  'sections.setTitlePage',
  'sections.setVerticalAlign',
  'selection.current',
  'styles.apply',
  'styles.paragraph.clearStyle',
  'styles.paragraph.setStyle',
  'tables.applyBorderPreset',
  'tables.clearBorder',
  'tables.clearCellSpacing',
  'tables.clearContents',
  'tables.clearDefaultStyle',
  'tables.clearShading',
  'tables.clearStyle',
  'tables.convertFromText',
  'tables.convertToText',
  'tables.delete',
  'tables.deleteCell',
  'tables.deleteColumn',
  'tables.deleteRow',
  'tables.distributeColumns',
  'tables.distributeRows',
  'tables.get',
  'tables.getCells',
  'tables.getProperties',
  'tables.getStyles',
  'tables.insertCell',
  'tables.insertColumn',
  'tables.insertRow',
  'tables.mergeCells',
  'tables.move',
  'tables.setAltText',
  'tables.setBorder',
  'tables.setBorders',
  'tables.setCellPadding',
  'tables.setCellSpacing',
  'tables.setColumnWidth',
  'tables.setDefaultStyle',
  'tables.setLayout',
  'tables.setRowHeight',
  'tables.setRowOptions',
  'tables.setShading',
  'tables.setStyle',
  'tables.setStyleOption',
  'tables.setTableOptions',
  'tables.setTablePadding',
  'tables.sort',
  'tables.split',
  'tables.splitCell',
  'tables.unmergeCells',
  'toc.configure',
  'toc.editEntry',
  'toc.get',
  'toc.getEntry',
  'toc.list',
  'toc.listEntries',
  'toc.markEntry',
  'toc.remove',
  'toc.unmarkEntry',
  'toc.update',
  'trackChanges.decide',
  'trackChanges.get',
  'trackChanges.list',
] as const;

export type OperationId = typeof OPERATIONS[number];

export const OPERATION_DESCRIPTIONS: Record<string, string> = {
  'authorities.configure': "Update the configuration of an existing table-of-authorities block.",
  'authorities.entries.get': "Get detailed information about a specific TA authority entry.",
  'authorities.entries.insert': "Insert a new TA authority entry field at a target location.",
  'authorities.entries.list': "List all TA (authority entry) fields in the document.",
  'authorities.entries.remove': "Remove a TA authority entry field from the document.",
  'authorities.entries.update': "Update the properties of an existing TA authority entry.",
  'authorities.get': "Get detailed information about a specific table-of-authorities block.",
  'authorities.insert': "Insert a new table-of-authorities block at a target location.",
  'authorities.list': "List all table-of-authorities blocks in the document.",
  'authorities.rebuild': "Rebuild a table-of-authorities block from its entries.",
  'authorities.remove': "Remove a table-of-authorities block from the document.",
  'blocks.delete': "Delete an entire block node (paragraph, heading, list item, table, image, or sdt) deterministically.",
  'blocks.deleteRange': "Delete a contiguous range of top-level blocks between two endpoints (inclusive). Both endpoints must be direct children of the document node. Supports dry-run preview.",
  'blocks.list': "List top-level blocks in document order with IDs, types, text previews, and optional full text when includeText:true. Supports pagination via offset/limit and optional nodeType filtering.",
  'bookmarks.get': "Get detailed information about a specific bookmark.",
  'bookmarks.insert': "Insert a new named bookmark at a target location.",
  'bookmarks.list': "List all bookmarks in the document.",
  'bookmarks.remove': "Remove a bookmark from the document.",
  'bookmarks.rename': "Rename an existing bookmark.",
  'capabilities.get': "Query runtime capabilities supported by the current document engine.",
  'captions.configure': "Configure numbering format for a caption label.",
  'captions.get': "Get detailed information about a specific caption paragraph.",
  'captions.insert': "Insert a new caption paragraph adjacent to a target block.",
  'captions.list': "List all caption paragraphs in the document.",
  'captions.remove': "Remove a caption paragraph from the document.",
  'captions.update': "Update the text of an existing caption paragraph.",
  'citations.bibliography.configure': "Configure the bibliography style.",
  'citations.bibliography.get': "Get information about the bibliography block.",
  'citations.bibliography.insert': "Insert a bibliography block at a target location.",
  'citations.bibliography.rebuild': "Rebuild the bibliography from current sources.",
  'citations.bibliography.remove': "Remove the bibliography block from the document.",
  'citations.get': "Get detailed information about a specific citation mark.",
  'citations.insert': "Insert a new citation mark at a target location.",
  'citations.list': "List all citation marks in the document.",
  'citations.remove': "Remove a citation mark from the document.",
  'citations.sources.get': "Get detailed information about a specific citation source.",
  'citations.sources.insert': "Register a new citation source in the document store.",
  'citations.sources.list': "List all citation sources in the document store.",
  'citations.sources.remove': "Remove a citation source from the document store.",
  'citations.sources.update': "Update the fields of an existing citation source.",
  'citations.update': "Update an existing citation mark's source references.",
  'comments.create': "Create a new comment thread (or reply when parentCommentId is given).",
  'comments.delete': "Remove a comment or reply by ID.",
  'comments.get': "Retrieve a single comment thread by ID.",
  'comments.list': "List all comment threads in the document.",
  'comments.patch': "Patch fields on an existing comment (text, target, status, or isInternal).",
  'contentControls.appendContent': "Append content to the end of a content control.",
  'contentControls.checkbox.getState': "Get the checked state of a checkbox content control.",
  'contentControls.checkbox.setState': "Set the checked state of a checkbox content control.",
  'contentControls.checkbox.setSymbolPair': "Set the checked and unchecked symbol glyphs for a checkbox content control.",
  'contentControls.checkbox.toggle': "Toggle the checked state of a checkbox content control.",
  'contentControls.choiceList.getItems': "Get the list items and selected value of a comboBox or dropDownList content control.",
  'contentControls.choiceList.setItems': "Replace the list items of a comboBox or dropDownList content control.",
  'contentControls.choiceList.setSelected': "Set the selected value of a comboBox or dropDownList content control.",
  'contentControls.clearBinding': "Remove data binding metadata from a content control.",
  'contentControls.clearContent': "Clear all content inside a content control, leaving it empty.",
  'contentControls.copy': "Copy a content control to a destination position. Copied SDTs receive new IDs.",
  'contentControls.date.clearValue': "Clear the date value of a date content control.",
  'contentControls.date.setCalendar': "Set the calendar type for a date content control.",
  'contentControls.date.setDisplayFormat': "Set the display format string for a date content control.",
  'contentControls.date.setDisplayLocale': "Set the display locale for a date content control.",
  'contentControls.date.setStorageFormat': "Set the XML storage format for a date content control.",
  'contentControls.date.setValue': "Set the date value of a date content control.",
  'contentControls.delete': "Delete a content control and its content from the document.",
  'contentControls.get': "Retrieve a single content control by target.",
  'contentControls.getBinding': "Get the data binding metadata (w:dataBinding) of a content control.",
  'contentControls.getContent': "Get the text content of a content control.",
  'contentControls.getParent': "Get the parent content control of the target, if any.",
  'contentControls.getRawProperties': "Get the raw sdtPr properties of a content control as a passthrough hash.",
  'contentControls.group.ungroup': "Remove the group designation from a group content control.",
  'contentControls.group.wrap': "Wrap a content control inside a new group content control. Always nests; not idempotent.",
  'contentControls.insertAfter': "Insert content immediately after a content control.",
  'contentControls.insertBefore': "Insert content immediately before a content control.",
  'contentControls.list': "List all content controls in the document with optional type/tag filtering.",
  'contentControls.listChildren': "List direct child content controls nested inside the target.",
  'contentControls.listInRange': "List content controls within a block range.",
  'contentControls.move': "Move a content control to a new position. Preserves original IDs.",
  'contentControls.normalizeTagPayload': "Normalize a content control tag between plain-string and JSON-encoded formats.",
  'contentControls.normalizeWordCompatibility': "Normalize a content control to resolve Word compatibility issues.",
  'contentControls.patch': "Patch metadata properties on a content control (tag, alias, appearance, color, etc.).",
  'contentControls.patchRawProperties': "Apply raw XML-level patches to the sdtPr subtree of a content control.",
  'contentControls.prependContent': "Prepend content to the beginning of a content control.",
  'contentControls.repeatingSection.cloneItem': "Clone a repeating section item at the given index. Cloned SDTs receive new IDs.",
  'contentControls.repeatingSection.deleteItem': "Delete a repeating section item at the given index.",
  'contentControls.repeatingSection.insertItemAfter': "Insert a new item after a specific index in a repeating section.",
  'contentControls.repeatingSection.insertItemBefore': "Insert a new item before a specific index in a repeating section.",
  'contentControls.repeatingSection.listItems': "List the repeating section items inside a repeating section content control.",
  'contentControls.repeatingSection.setAllowInsertDelete': "Set the allowInsertDelete flag on a repeating section.",
  'contentControls.replaceContent': "Replace the entire content of a content control.",
  'contentControls.selectByTag': "Select content controls matching a specific tag value.",
  'contentControls.selectByTitle': "Select content controls matching a specific title (alias) value.",
  'contentControls.setBinding': "Set data binding metadata on a content control.",
  'contentControls.setLockMode': "Set the lock mode on a content control.",
  'contentControls.setType': "Transition a content control to a different semantic type. Metadata-only; no implicit content rewrite.",
  'contentControls.text.clearValue': "Clear the text value of a plain-text content control.",
  'contentControls.text.setMultiline': "Set or clear the multiline attribute on a plain-text content control.",
  'contentControls.text.setValue': "Set the text value of a plain-text content control.",
  'contentControls.unwrap': "Remove the content control wrapper, preserving its content in place.",
  'contentControls.validateWordCompatibility': "Validate a content control for Word compatibility issues.",
  'contentControls.wrap': "Wrap existing content with a new content control.",
  'create.contentControl': "Create a new content control (SDT) in the document.",
  'create.heading': "Create a new heading at the target position.",
  'create.image': "Insert a new image at the target position.",
  'create.paragraph': "Create a standalone paragraph at the target position. To add a list item, use lists.insert instead.",
  'create.sectionBreak': "Create a section break at the target location with optional initial section properties.",
  'create.table': "Create a new table at the target position.",
  'create.tableOfContents': "Insert a new table of contents at the target position.",
  'crossRefs.get': "Get detailed information about a specific cross-reference field.",
  'crossRefs.insert': "Insert a new cross-reference field at a target location.",
  'crossRefs.list': "List all cross-reference fields in the document.",
  'crossRefs.rebuild': "Rebuild (recalculate) a cross-reference field.",
  'crossRefs.remove': "Remove a cross-reference field from the document.",
  'customXml.parts.create': "Add a new Custom XML Data Storage Part to the document. Generates a fresh itemID GUID and emits the Properties Part.",
  'customXml.parts.list': "List Custom XML Data Storage Parts in the document, optionally filtered by root namespace or schema reference.",
  'fields.get': "Get detailed information about a specific field.",
  'fields.insert': "Insert a raw field code at a target location.",
  'fields.list': "List all fields in the document.",
  'fields.rebuild': "Rebuild (recalculate) a field.",
  'fields.remove': "Remove a field from the document.",
  'footnotes.configure': "Configure numbering and placement for footnotes or endnotes.",
  'footnotes.get': "Get detailed information about a specific footnote or endnote.",
  'footnotes.insert': "Insert a new footnote or endnote at a target location.",
  'footnotes.list': "List all footnotes and endnotes in the document.",
  'footnotes.remove': "Remove a footnote or endnote from the document.",
  'footnotes.update': "Update the content of an existing footnote or endnote.",
  'format.apply': "Apply inline run-property patch changes to the target range with explicit set/clear semantics.",
  'format.paragraph.clearAlignment': "Remove direct paragraph alignment, reverting to style-defined or default alignment.",
  'format.paragraph.clearAllTabStops': "Remove all tab stops from a paragraph.",
  'format.paragraph.clearBorder': "Remove border for a specific side or all sides of a paragraph.",
  'format.paragraph.clearDirection': "Remove explicit paragraph direction, reverting to inherited or default (LTR).",
  'format.paragraph.clearIndentation': "Remove all direct paragraph indentation.",
  'format.paragraph.clearShading': "Remove all paragraph shading.",
  'format.paragraph.clearSpacing': "Remove all direct paragraph spacing.",
  'format.paragraph.clearTabStop': "Remove a tab stop at a given position.",
  'format.paragraph.resetDirectFormatting': "Strip all direct paragraph formatting while preserving style reference, numbering, and section metadata.",
  'format.paragraph.setAlignment': "Set visual paragraph alignment on a paragraph-like block. For RTL paragraphs, left/right are translated to Word-compatible stored justification values.",
  'format.paragraph.setBorder': "Set border properties for a specific side of a paragraph.",
  'format.paragraph.setDirection': "Set paragraph base direction (LTR or RTL via w:bidi). Optionally align text to match.",
  'format.paragraph.setFlowOptions': "Set contextual spacing, page-break-before, and suppress-auto-hyphens flags.",
  'format.paragraph.setIndentation': "Set paragraph indentation properties (left, right, firstLine, hanging) in twips.",
  'format.paragraph.setKeepOptions': "Set keep-with-next, keep-lines-together, and widow/orphan control flags.",
  'format.paragraph.setOutlineLevel': "Set the paragraph outline level (0–9) or null to clear.",
  'format.paragraph.setShading': "Set paragraph shading (background fill, pattern color, pattern type).",
  'format.paragraph.setSpacing': "Set paragraph spacing properties (before, after, line, lineRule) in twips.",
  'format.paragraph.setTabStop': "Add or replace a tab stop at a given position.",
  'headerFooters.get': "Get a single header/footer slot entry by address.",
  'headerFooters.list': "List header/footer slot entries across sections.",
  'headerFooters.parts.create': "Create a new independent header/footer part, optionally cloned from an existing part.",
  'headerFooters.parts.delete': "Delete a header/footer part and its associated relationship when no section slots reference it.",
  'headerFooters.parts.list': "List unique header/footer part records from document relationships.",
  'headerFooters.refs.clear': "Clear an explicit header/footer reference from a section slot.",
  'headerFooters.refs.set': "Set an explicit header/footer reference on a section slot.",
  'headerFooters.refs.setLinkedToPrevious': "Link or unlink a header/footer slot to/from the previous section.",
  'headerFooters.resolve': "Resolve the effective header/footer reference for a slot, walking the section inheritance chain.",
  'history.get': "Query the current undo/redo history state of the document.",
  'history.redo': "Redo the most recently undone action in the document.",
  'history.undo': "Undo the most recent history-safe mutation in the document.",
  'hyperlinks.get': "Retrieve details of a specific hyperlink by its inline address.",
  'hyperlinks.insert': "Insert new linked text at a target position.",
  'hyperlinks.list': "List all hyperlinks in the document, with optional filtering by href, anchor, or display text.",
  'hyperlinks.patch': "Update hyperlink metadata (destination, tooltip, target, rel) without changing display text.",
  'hyperlinks.remove': "Remove a hyperlink. Mode 'unwrap' preserves display text; 'deleteText' removes the linked content entirely.",
  'hyperlinks.wrap': "Wrap an existing text range with a hyperlink.",
  'images.convertToFloating': "Convert an inline image to floating placement.",
  'images.convertToInline': "Convert a floating image to inline placement.",
  'images.crop': "Apply rectangular edge-percentage crop to an image.",
  'images.delete': "Delete an image from the document.",
  'images.flip': "Set horizontal and/or vertical flip state for an image.",
  'images.get': "Get details for a specific image by its stable ID.",
  'images.insertCaption': "Insert a caption paragraph below the image.",
  'images.list': "List all images in the document.",
  'images.move': "Move an image to a new location in the document.",
  'images.removeCaption': "Remove the caption paragraph from below the image.",
  'images.replaceSource': "Replace the image source while preserving identity and placement.",
  'images.resetCrop': "Remove all cropping from an image.",
  'images.rotate': "Set the absolute rotation angle for an image.",
  'images.scale': "Scale an image by a uniform factor applied to both dimensions.",
  'images.setAltText': "Set the accessibility description (alt text) for an image.",
  'images.setAnchorOptions': "Set anchor behavior options for a floating image.",
  'images.setDecorative': "Mark or unmark an image as decorative.",
  'images.setHyperlink': "Set or remove the hyperlink attached to an image.",
  'images.setLockAspectRatio': "Lock or unlock the aspect ratio for an image.",
  'images.setName': "Set the object name for an image.",
  'images.setPosition': "Set the anchor position for a floating image.",
  'images.setSize': "Set explicit width/height for an image.",
  'images.setWrapDistances': "Set the text-wrap distance margins for a floating image.",
  'images.setWrapSide': "Set which side(s) text wraps around a floating image.",
  'images.setWrapType': "Set the text wrapping type for a floating image.",
  'images.setZOrder': "Set the z-order (relativeHeight) for a floating image.",
  'images.updateCaption': "Update the text of an existing caption paragraph.",
  'index.configure': "Update the configuration of an existing index block.",
  'index.entries.get': "Get detailed information about a specific XE index entry.",
  'index.entries.insert': "Insert a new XE index entry field at a target location.",
  'index.entries.list': "List all XE (index entry) fields in the document.",
  'index.entries.remove': "Remove an XE index entry field from the document.",
  'index.entries.update': "Update the properties of an existing XE index entry.",
  'index.get': "Get detailed information about a specific index block.",
  'index.insert': "Insert a new index block at a target location.",
  'index.list': "List all index blocks in the document.",
  'index.rebuild': "Rebuild (regenerate) an index block from its entries.",
  'index.remove': "Remove an index block from the document.",
  'lists.applyPreset': "Apply a built-in list formatting preset to the target list.",
  'lists.applyStyle': "Apply a reusable list style to the target list. Sequence-local: if the abstract definition is shared with other lists, it is cloned first to avoid affecting them.",
  'lists.applyTemplate': "Advanced alias for lists.applyStyle. Apply a captured ListTemplate to the target list (abstract-scoped, no clone-on-write).",
  'lists.attach': "Convert non-list paragraphs to list items under an existing list sequence.",
  'lists.canContinuePrevious': "Check whether the target sequence can continue numbering from a previous compatible sequence.",
  'lists.canJoin': "Check whether two adjacent list sequences can be joined.",
  'lists.captureTemplate': "Advanced alias for lists.getStyle. Capture list formatting from the abstract definition only (does not merge lvlOverride formatting).",
  'lists.clearLevelOverrides': "Remove instance-level overrides for a specific list level, restoring abstract definition values.",
  'lists.continuePrevious': "Continue numbering from the nearest compatible previous list sequence.",
  'lists.convertToText': "Convert list items to plain paragraphs, optionally prepending the rendered marker text.",
  'lists.create': "Create a new list from one or more paragraphs. Supports optional preset or style for new sequences. When sequence.mode is \\",
  'lists.detach': "Remove numbering properties from list items, converting them to plain paragraphs.",
  'lists.get': "Retrieve a specific list node by target.",
  'lists.getStyle': "Read the effective reusable style of a list, including instance-level overrides. Returns a ListStyle that can be applied to other lists via lists.applyStyle.",
  'lists.indent': "Increase the indentation level of a list item.",
  'lists.insert': "Insert a new list item before or after an existing list item. The new item inherits the target list context.",
  'lists.join': "Merge two adjacent list sequences into one.",
  'lists.list': "List all list nodes in the document, optionally filtered by scope.",
  'lists.merge': "Compound: merge two adjacent list sequences into one. Reassigns numId on the absorbed sequence (no strict abstractNumId check: absorbed items adopt the absorbing definition) and deletes empty paragraphs between the two sequences. Use this instead of lists.join for the user-facing \\",
  'lists.outdent': "Decrease the indentation level of a list item.",
  'lists.restartAt': "Restart numbering at the target list item with a specific value. If the item is mid-sequence, it is separated first.",
  'lists.separate': "Split a list sequence at the target item, creating a new sequence from that point forward.",
  'lists.setLevel': "Set the absolute nesting level (0..8) of a list item.",
  'lists.setLevelAlignment': "Set the marker alignment (left, center, right) for a specific list level.",
  'lists.setLevelBullet': "Set the bullet marker text for a specific list level.",
  'lists.setLevelIndents': "Set the paragraph indentation values (left, hanging, firstLine) for a specific list level.",
  'lists.setLevelLayout': "Set the layout properties (alignment, indentation, trailing character, tab stop) for a specific list level. Accepts partial updates: omitted fields are left unchanged. Sequence-local: clones shared definitions.",
  'lists.setLevelMarkerFont': "Set the font family used for the marker character at a specific list level.",
  'lists.setLevelNumbering': "Advanced alias for lists.setLevelNumberStyle/setLevelText/setLevelStart. Set format, pattern, and start in one call (abstract-scoped, no clone-on-write).",
  'lists.setLevelNumberStyle': "Set the numbering style (e.g. decimal, lowerLetter, upperRoman) for a specific list level. Rejects \\",
  'lists.setLevelPictureBullet': "Set a picture bullet for a specific list level by its OOXML lvlPicBulletId.",
  'lists.setLevelRestart': "Set the restart behavior for a specific list level.",
  'lists.setLevelStart': "Set the start value for a specific list level. Rejects bullet levels and non-positive values. Sequence-local: clones shared definitions.",
  'lists.setLevelText': "Set the level text pattern (e.g. \\",
  'lists.setLevelTrailingCharacter': "Set the trailing character (tab, space, nothing) after the marker for a specific list level.",
  'lists.setType': "Convert a list to ordered or bullet and merge adjacent compatible sequences to preserve continuous numbering.",
  'lists.setValue': "Set an explicit numbering value at the target item. Mid-sequence targets are atomically separated first.",
  'lists.split': "Compound: split a list sequence at the target item into two independent sequences. Runs lists.separate then (by default) lists.setValue(1) so the new half starts numbering fresh at 1. Pass restartNumbering:false for raw separate semantics (new half continues the previous count).",
  'metadata.get': "Get a single anchored-metadata entry by id, including its JSON payload.",
  'metadata.list': "List anchored-metadata entries in the document, optionally filtered by consumer namespace and/or a `within` selection (returns only entries whose anchor overlaps `within`).",
  'metadata.remove': "Remove an anchored-metadata entry. Strips the anchor content-control wrapper (its content stays in the document) and deletes the payload entry from the Storage Part. In v1 these writes are sequenced, not transactional: the adapter resolves the target up-front so missing-target failures land before any state change, but a crash strictly between the two writes can leave a dangling payload. When the backing part has no remaining entries, the part itself is removed.",
  'metadata.resolve': "Find where an anchored-metadata entry is anchored in the document. Returns the SelectionTarget covering the anchor content.",
  'metadata.update': "Replace the JSON payload of an existing anchored-metadata entry. Replace semantics; no merge. The anchor is left untouched.",
  'mutations.apply': "Execute a mutation plan atomically against the document.",
  'mutations.preview': "Dry-run a mutation plan, returning resolved targets without applying changes.",
  'permissionRanges.create': "Create a permission range exception region in the document. Inserts matched permStart/permEnd markers at the target.",
  'permissionRanges.get': "Get detailed information about a specific permission range by ID.",
  'permissionRanges.list': "List all permission ranges in the document. Returns only complete paired ranges (both start and end markers present).",
  'permissionRanges.remove': "Remove a permission range by ID. Removes whichever markers exist for the given ID (start, end, or both).",
  'permissionRanges.updatePrincipal': "Change which principal is allowed to edit a permission range. Updates the principal fields on the start marker.",
  'protection.clearEditingRestriction': "Disable document-level editing restriction by setting enforcement to off. Preserves the protection element and its metadata for round-trip fidelity.",
  'protection.get': "Read the current document protection state including editing restrictions, write protection, and read-only recommendation.",
  'protection.setEditingRestriction': "Enable Word-style editing restriction on the document. Only readOnly mode is supported in v1.",
  'query.match': "Deterministic selector-based search returning mutation-grade addresses and text ranges. Use this to discover targets before any mutation.",
  'ranges.resolve': "Resolve two explicit anchors into a contiguous document range. Returns a transparent SelectionTarget, a mutation-ready ref, and preview metadata. Stateless and deterministic.",
  'sections.clearHeaderFooterRef': "Clear a section header/footer reference for a specific variant.",
  'sections.clearPageBorders': "Clear page border configuration for a section.",
  'sections.get': "Retrieve full section information by section address.",
  'sections.list': "List sections in deterministic order with section-target handles.",
  'sections.setBreakType': "Set the section break type.",
  'sections.setColumns': "Set column configuration for a section.",
  'sections.setHeaderFooterMargins': "Set header/footer margin distances for a section.",
  'sections.setHeaderFooterRef': "Set or replace a section header/footer reference for a variant.",
  'sections.setLineNumbering': "Enable or configure line numbering for a section.",
  'sections.setLinkToPrevious': "Set or clear link-to-previous behavior for a header/footer variant.",
  'sections.setOddEvenHeadersFooters': "Enable or disable odd/even header-footer mode in document settings.",
  'sections.setPageBorders': "Set page border configuration for a section.",
  'sections.setPageMargins': "Set page-edge margins for a section.",
  'sections.setPageNumbering': "Set page numbering format/start for a section.",
  'sections.setPageSetup': "Set page size/orientation properties for a section.",
  'sections.setSectionDirection': "Set section text flow direction (LTR/RTL).",
  'sections.setTitlePage': "Enable or disable title-page behavior for a section.",
  'sections.setVerticalAlign': "Set vertical page alignment for a section.",
  'selection.current': "Read the editor's current selection as a portable SelectionInfo with a text-anchored TextTarget. Primitive for building custom comments UIs, floating toolbars, and other selection-driven components without reaching into ProseMirror internals.",
  'styles.apply': "Apply document-level default style changes to the stylesheet (word/styles.xml). Targets docDefaults run and paragraph channels with set-style patch semantics.",
  'styles.paragraph.clearStyle': "Remove the paragraph style reference from a paragraph-like block.",
  'styles.paragraph.setStyle': "Apply a paragraph style (w:pStyle) to a paragraph-like block, clearing direct run formatting while preserving character-style references.",
  'tables.applyBorderPreset': "Apply a border preset (e.g. all borders, outside only) to a table.",
  'tables.clearBorder': "Remove border formatting from a table or cell range.",
  'tables.clearCellSpacing': "Remove custom cell spacing from the target table.",
  'tables.clearContents': "Clear the contents of the target table or cell range.",
  'tables.clearDefaultStyle': "Remove the document-level default table style setting.",
  'tables.clearShading': "Remove shading from a table or cell range.",
  'tables.clearStyle': "Remove the applied table style, reverting to defaults.",
  'tables.convertFromText': "Convert a text range into a table.",
  'tables.convertToText': "Convert a table back to plain text.",
  'tables.delete': "Delete the target table from the document.",
  'tables.deleteCell': "Delete a cell from a table row.",
  'tables.deleteColumn': "Delete a column from the target table.",
  'tables.deleteRow': "Delete a row from the target table.",
  'tables.distributeColumns': "Distribute column widths evenly across the target table.",
  'tables.distributeRows': "Distribute row heights evenly across the target table.",
  'tables.get': "Retrieve table structure and dimensions by locator.",
  'tables.getCells': "Retrieve cell information for a table, optionally filtered by row or column.",
  'tables.getProperties': "Retrieve layout and style properties of a table.",
  'tables.getStyles': "List all table styles and the document-level default table style setting.",
  'tables.insertCell': "Insert a new cell into a table row.",
  'tables.insertColumn': "Insert a new column into the target table. The new column is cloned from an adjacent column, so it inherits the existing cell shading, borders, alignment, and width. No follow-up styling call is needed unless the new column should look different from the rest of the table.",
  'tables.insertRow': "Insert a new row into the target table. The new row is cloned from an adjacent row, so it inherits the existing cell shading, borders, alignment, and padding. No follow-up styling call is needed unless the new row should look different from the rest of the table.",
  'tables.mergeCells': "Merge a range of table cells into one.",
  'tables.move': "Move a table to a new position in the document.",
  'tables.setAltText': "Set the alternative text description for a table.",
  'tables.setBorder': "Set border properties on a table or cell range.",
  'tables.setBorders': "Set borders on a table using a target set or per-edge patch.",
  'tables.setCellPadding': "Set padding on a specific table cell or cell range.",
  'tables.setCellSpacing': "Set the cell spacing for the target table.",
  'tables.setColumnWidth': "Set the width of a table column.",
  'tables.setDefaultStyle': "Set the document-level default table style (w:defaultTableStyle in settings.xml).",
  'tables.setLayout': "Set the layout mode of the target table.",
  'tables.setRowHeight': "Set the height of a table row.",
  'tables.setRowOptions': "Set options on a table row such as header repeat or page break.",
  'tables.setShading': "Set the background shading color on a table or cell range.",
  'tables.setStyle': "Apply a named table style to the target table.",
  'tables.setStyleOption': "Toggle a conditional style option such as banded rows or first column.",
  'tables.setTableOptions': "Set table-level default cell margins and/or cell spacing.",
  'tables.setTablePadding': "Set default cell padding for the entire table.",
  'tables.sort': "Sort table rows by a column value.",
  'tables.split': "Split a table into two tables at the target row.",
  'tables.splitCell': "Split a table cell into multiple cells.",
  'tables.unmergeCells': "Unmerge a previously merged table cell.",
  'toc.configure': "Update the configuration switches of a table of contents.",
  'toc.editEntry': "Update the properties of a TC (table of contents entry) field.",
  'toc.get': "Retrieve details of a specific table of contents.",
  'toc.getEntry': "Retrieve details of a specific TC (table of contents entry) field.",
  'toc.list': "List all tables of contents in the document.",
  'toc.listEntries': "List all TC (table of contents entry) fields in the document body.",
  'toc.markEntry': "Insert a TC (table of contents entry) field at the target paragraph.",
  'toc.remove': "Remove a table of contents from the document.",
  'toc.unmarkEntry': "Remove a TC (table of contents entry) field from the document.",
  'toc.update': "Rebuild or refresh the materialized content of a table of contents.",
  'trackChanges.decide': "Accept or reject tracked changes by ID, range, or scope: all (optionally filtered by story).",
  'trackChanges.get': "Retrieve a single tracked change by ID.",
  'trackChanges.list': "List all tracked changes in the document.",
};

export const OPERATION_GROUPS: Record<string, string> = {
  'authorities.configure': 'authorities',
  'authorities.entries.get': 'authorities',
  'authorities.entries.insert': 'authorities',
  'authorities.entries.list': 'authorities',
  'authorities.entries.remove': 'authorities',
  'authorities.entries.update': 'authorities',
  'authorities.get': 'authorities',
  'authorities.insert': 'authorities',
  'authorities.list': 'authorities',
  'authorities.rebuild': 'authorities',
  'authorities.remove': 'authorities',
  'blocks.delete': 'blocks',
  'blocks.deleteRange': 'blocks',
  'blocks.list': 'blocks',
  'bookmarks.get': 'bookmarks',
  'bookmarks.insert': 'bookmarks',
  'bookmarks.list': 'bookmarks',
  'bookmarks.remove': 'bookmarks',
  'bookmarks.rename': 'bookmarks',
  'capabilities.get': 'capabilities',
  'captions.configure': 'captions',
  'captions.get': 'captions',
  'captions.insert': 'captions',
  'captions.list': 'captions',
  'captions.remove': 'captions',
  'captions.update': 'captions',
  'citations.bibliography.configure': 'citations',
  'citations.bibliography.get': 'citations',
  'citations.bibliography.insert': 'citations',
  'citations.bibliography.rebuild': 'citations',
  'citations.bibliography.remove': 'citations',
  'citations.get': 'citations',
  'citations.insert': 'citations',
  'citations.list': 'citations',
  'citations.remove': 'citations',
  'citations.sources.get': 'citations',
  'citations.sources.insert': 'citations',
  'citations.sources.list': 'citations',
  'citations.sources.remove': 'citations',
  'citations.sources.update': 'citations',
  'citations.update': 'citations',
  'comments.create': 'comments',
  'comments.delete': 'comments',
  'comments.get': 'comments',
  'comments.list': 'comments',
  'comments.patch': 'comments',
  'contentControls.appendContent': 'contentControls',
  'contentControls.checkbox.getState': 'contentControls',
  'contentControls.checkbox.setState': 'contentControls',
  'contentControls.checkbox.setSymbolPair': 'contentControls',
  'contentControls.checkbox.toggle': 'contentControls',
  'contentControls.choiceList.getItems': 'contentControls',
  'contentControls.choiceList.setItems': 'contentControls',
  'contentControls.choiceList.setSelected': 'contentControls',
  'contentControls.clearBinding': 'contentControls',
  'contentControls.clearContent': 'contentControls',
  'contentControls.copy': 'contentControls',
  'contentControls.date.clearValue': 'contentControls',
  'contentControls.date.setCalendar': 'contentControls',
  'contentControls.date.setDisplayFormat': 'contentControls',
  'contentControls.date.setDisplayLocale': 'contentControls',
  'contentControls.date.setStorageFormat': 'contentControls',
  'contentControls.date.setValue': 'contentControls',
  'contentControls.delete': 'contentControls',
  'contentControls.get': 'contentControls',
  'contentControls.getBinding': 'contentControls',
  'contentControls.getContent': 'contentControls',
  'contentControls.getParent': 'contentControls',
  'contentControls.getRawProperties': 'contentControls',
  'contentControls.group.ungroup': 'contentControls',
  'contentControls.group.wrap': 'contentControls',
  'contentControls.insertAfter': 'contentControls',
  'contentControls.insertBefore': 'contentControls',
  'contentControls.list': 'contentControls',
  'contentControls.listChildren': 'contentControls',
  'contentControls.listInRange': 'contentControls',
  'contentControls.move': 'contentControls',
  'contentControls.normalizeTagPayload': 'contentControls',
  'contentControls.normalizeWordCompatibility': 'contentControls',
  'contentControls.patch': 'contentControls',
  'contentControls.patchRawProperties': 'contentControls',
  'contentControls.prependContent': 'contentControls',
  'contentControls.repeatingSection.cloneItem': 'contentControls',
  'contentControls.repeatingSection.deleteItem': 'contentControls',
  'contentControls.repeatingSection.insertItemAfter': 'contentControls',
  'contentControls.repeatingSection.insertItemBefore': 'contentControls',
  'contentControls.repeatingSection.listItems': 'contentControls',
  'contentControls.repeatingSection.setAllowInsertDelete': 'contentControls',
  'contentControls.replaceContent': 'contentControls',
  'contentControls.selectByTag': 'contentControls',
  'contentControls.selectByTitle': 'contentControls',
  'contentControls.setBinding': 'contentControls',
  'contentControls.setLockMode': 'contentControls',
  'contentControls.setType': 'contentControls',
  'contentControls.text.clearValue': 'contentControls',
  'contentControls.text.setMultiline': 'contentControls',
  'contentControls.text.setValue': 'contentControls',
  'contentControls.unwrap': 'contentControls',
  'contentControls.validateWordCompatibility': 'contentControls',
  'contentControls.wrap': 'contentControls',
  'create.contentControl': 'contentControls',
  'create.heading': 'create',
  'create.image': 'create',
  'create.paragraph': 'create',
  'create.sectionBreak': 'create',
  'create.table': 'create',
  'create.tableOfContents': 'create',
  'crossRefs.get': 'crossRefs',
  'crossRefs.insert': 'crossRefs',
  'crossRefs.list': 'crossRefs',
  'crossRefs.rebuild': 'crossRefs',
  'crossRefs.remove': 'crossRefs',
  'customXml.parts.create': 'customXml',
  'customXml.parts.list': 'customXml',
  'fields.get': 'fields',
  'fields.insert': 'fields',
  'fields.list': 'fields',
  'fields.rebuild': 'fields',
  'fields.remove': 'fields',
  'footnotes.configure': 'footnotes',
  'footnotes.get': 'footnotes',
  'footnotes.insert': 'footnotes',
  'footnotes.list': 'footnotes',
  'footnotes.remove': 'footnotes',
  'footnotes.update': 'footnotes',
  'format.apply': 'format',
  'format.paragraph.clearAlignment': 'format.paragraph',
  'format.paragraph.clearAllTabStops': 'format.paragraph',
  'format.paragraph.clearBorder': 'format.paragraph',
  'format.paragraph.clearDirection': 'format.paragraph',
  'format.paragraph.clearIndentation': 'format.paragraph',
  'format.paragraph.clearShading': 'format.paragraph',
  'format.paragraph.clearSpacing': 'format.paragraph',
  'format.paragraph.clearTabStop': 'format.paragraph',
  'format.paragraph.resetDirectFormatting': 'format.paragraph',
  'format.paragraph.setAlignment': 'format.paragraph',
  'format.paragraph.setBorder': 'format.paragraph',
  'format.paragraph.setDirection': 'format.paragraph',
  'format.paragraph.setFlowOptions': 'format.paragraph',
  'format.paragraph.setIndentation': 'format.paragraph',
  'format.paragraph.setKeepOptions': 'format.paragraph',
  'format.paragraph.setOutlineLevel': 'format.paragraph',
  'format.paragraph.setShading': 'format.paragraph',
  'format.paragraph.setSpacing': 'format.paragraph',
  'format.paragraph.setTabStop': 'format.paragraph',
  'headerFooters.get': 'headerFooters',
  'headerFooters.list': 'headerFooters',
  'headerFooters.parts.create': 'headerFooters',
  'headerFooters.parts.delete': 'headerFooters',
  'headerFooters.parts.list': 'headerFooters',
  'headerFooters.refs.clear': 'headerFooters',
  'headerFooters.refs.set': 'headerFooters',
  'headerFooters.refs.setLinkedToPrevious': 'headerFooters',
  'headerFooters.resolve': 'headerFooters',
  'history.get': 'history',
  'history.redo': 'history',
  'history.undo': 'history',
  'hyperlinks.get': 'hyperlinks',
  'hyperlinks.insert': 'hyperlinks',
  'hyperlinks.list': 'hyperlinks',
  'hyperlinks.patch': 'hyperlinks',
  'hyperlinks.remove': 'hyperlinks',
  'hyperlinks.wrap': 'hyperlinks',
  'images.convertToFloating': 'images',
  'images.convertToInline': 'images',
  'images.crop': 'images',
  'images.delete': 'images',
  'images.flip': 'images',
  'images.get': 'images',
  'images.insertCaption': 'images',
  'images.list': 'images',
  'images.move': 'images',
  'images.removeCaption': 'images',
  'images.replaceSource': 'images',
  'images.resetCrop': 'images',
  'images.rotate': 'images',
  'images.scale': 'images',
  'images.setAltText': 'images',
  'images.setAnchorOptions': 'images',
  'images.setDecorative': 'images',
  'images.setHyperlink': 'images',
  'images.setLockAspectRatio': 'images',
  'images.setName': 'images',
  'images.setPosition': 'images',
  'images.setSize': 'images',
  'images.setWrapDistances': 'images',
  'images.setWrapSide': 'images',
  'images.setWrapType': 'images',
  'images.setZOrder': 'images',
  'images.updateCaption': 'images',
  'index.configure': 'index',
  'index.entries.get': 'index',
  'index.entries.insert': 'index',
  'index.entries.list': 'index',
  'index.entries.remove': 'index',
  'index.entries.update': 'index',
  'index.get': 'index',
  'index.insert': 'index',
  'index.list': 'index',
  'index.rebuild': 'index',
  'index.remove': 'index',
  'lists.applyPreset': 'lists',
  'lists.applyStyle': 'lists',
  'lists.applyTemplate': 'lists',
  'lists.attach': 'lists',
  'lists.canContinuePrevious': 'lists',
  'lists.canJoin': 'lists',
  'lists.captureTemplate': 'lists',
  'lists.clearLevelOverrides': 'lists',
  'lists.continuePrevious': 'lists',
  'lists.convertToText': 'lists',
  'lists.create': 'lists',
  'lists.detach': 'lists',
  'lists.get': 'lists',
  'lists.getStyle': 'lists',
  'lists.indent': 'lists',
  'lists.insert': 'lists',
  'lists.join': 'lists',
  'lists.list': 'lists',
  'lists.merge': 'lists',
  'lists.outdent': 'lists',
  'lists.restartAt': 'lists',
  'lists.separate': 'lists',
  'lists.setLevel': 'lists',
  'lists.setLevelAlignment': 'lists',
  'lists.setLevelBullet': 'lists',
  'lists.setLevelIndents': 'lists',
  'lists.setLevelLayout': 'lists',
  'lists.setLevelMarkerFont': 'lists',
  'lists.setLevelNumbering': 'lists',
  'lists.setLevelNumberStyle': 'lists',
  'lists.setLevelPictureBullet': 'lists',
  'lists.setLevelRestart': 'lists',
  'lists.setLevelStart': 'lists',
  'lists.setLevelText': 'lists',
  'lists.setLevelTrailingCharacter': 'lists',
  'lists.setType': 'lists',
  'lists.setValue': 'lists',
  'lists.split': 'lists',
  'metadata.get': 'metadata',
  'metadata.list': 'metadata',
  'metadata.remove': 'metadata',
  'metadata.resolve': 'metadata',
  'metadata.update': 'metadata',
  'mutations.apply': 'mutations',
  'mutations.preview': 'mutations',
  'permissionRanges.create': 'permissionRanges',
  'permissionRanges.get': 'permissionRanges',
  'permissionRanges.list': 'permissionRanges',
  'permissionRanges.remove': 'permissionRanges',
  'permissionRanges.updatePrincipal': 'permissionRanges',
  'protection.clearEditingRestriction': 'protection',
  'protection.get': 'protection',
  'protection.setEditingRestriction': 'protection',
  'query.match': 'query',
  'ranges.resolve': 'ranges',
  'sections.clearHeaderFooterRef': 'sections',
  'sections.clearPageBorders': 'sections',
  'sections.get': 'sections',
  'sections.list': 'sections',
  'sections.setBreakType': 'sections',
  'sections.setColumns': 'sections',
  'sections.setHeaderFooterMargins': 'sections',
  'sections.setHeaderFooterRef': 'sections',
  'sections.setLineNumbering': 'sections',
  'sections.setLinkToPrevious': 'sections',
  'sections.setOddEvenHeadersFooters': 'sections',
  'sections.setPageBorders': 'sections',
  'sections.setPageMargins': 'sections',
  'sections.setPageNumbering': 'sections',
  'sections.setPageSetup': 'sections',
  'sections.setSectionDirection': 'sections',
  'sections.setTitlePage': 'sections',
  'sections.setVerticalAlign': 'sections',
  'selection.current': 'selection',
  'styles.apply': 'styles',
  'styles.paragraph.clearStyle': 'styles.paragraph',
  'styles.paragraph.setStyle': 'styles.paragraph',
  'tables.applyBorderPreset': 'tables',
  'tables.clearBorder': 'tables',
  'tables.clearCellSpacing': 'tables',
  'tables.clearContents': 'tables',
  'tables.clearDefaultStyle': 'tables',
  'tables.clearShading': 'tables',
  'tables.clearStyle': 'tables',
  'tables.convertFromText': 'tables',
  'tables.convertToText': 'tables',
  'tables.delete': 'tables',
  'tables.deleteCell': 'tables',
  'tables.deleteColumn': 'tables',
  'tables.deleteRow': 'tables',
  'tables.distributeColumns': 'tables',
  'tables.distributeRows': 'tables',
  'tables.get': 'tables',
  'tables.getCells': 'tables',
  'tables.getProperties': 'tables',
  'tables.getStyles': 'tables',
  'tables.insertCell': 'tables',
  'tables.insertColumn': 'tables',
  'tables.insertRow': 'tables',
  'tables.mergeCells': 'tables',
  'tables.move': 'tables',
  'tables.setAltText': 'tables',
  'tables.setBorder': 'tables',
  'tables.setBorders': 'tables',
  'tables.setCellPadding': 'tables',
  'tables.setCellSpacing': 'tables',
  'tables.setColumnWidth': 'tables',
  'tables.setDefaultStyle': 'tables',
  'tables.setLayout': 'tables',
  'tables.setRowHeight': 'tables',
  'tables.setRowOptions': 'tables',
  'tables.setShading': 'tables',
  'tables.setStyle': 'tables',
  'tables.setStyleOption': 'tables',
  'tables.setTableOptions': 'tables',
  'tables.setTablePadding': 'tables',
  'tables.sort': 'tables',
  'tables.split': 'tables',
  'tables.splitCell': 'tables',
  'tables.unmergeCells': 'tables',
  'toc.configure': 'toc',
  'toc.editEntry': 'toc',
  'toc.get': 'toc',
  'toc.getEntry': 'toc',
  'toc.list': 'toc',
  'toc.listEntries': 'toc',
  'toc.markEntry': 'toc',
  'toc.remove': 'toc',
  'toc.unmarkEntry': 'toc',
  'toc.update': 'toc',
  'trackChanges.decide': 'trackChanges',
  'trackChanges.get': 'trackChanges',
  'trackChanges.list': 'trackChanges',
};

// Operations grouped by category
export const GROUPS: Record<string, readonly string[]> = {
  'authorities': ['authorities.configure', 'authorities.entries.get', 'authorities.entries.insert', 'authorities.entries.list', 'authorities.entries.remove', 'authorities.entries.update', 'authorities.get', 'authorities.insert', 'authorities.list', 'authorities.rebuild', 'authorities.remove'],
  'blocks': ['blocks.delete', 'blocks.deleteRange', 'blocks.list'],
  'bookmarks': ['bookmarks.get', 'bookmarks.insert', 'bookmarks.list', 'bookmarks.remove', 'bookmarks.rename'],
  'capabilities': ['capabilities.get'],
  'captions': ['captions.configure', 'captions.get', 'captions.insert', 'captions.list', 'captions.remove', 'captions.update'],
  'citations': ['citations.bibliography.configure', 'citations.bibliography.get', 'citations.bibliography.insert', 'citations.bibliography.rebuild', 'citations.bibliography.remove', 'citations.get', 'citations.insert', 'citations.list', 'citations.remove', 'citations.sources.get', 'citations.sources.insert', 'citations.sources.list', 'citations.sources.remove', 'citations.sources.update', 'citations.update'],
  'comments': ['comments.create', 'comments.delete', 'comments.get', 'comments.list', 'comments.patch'],
  'contentControls': ['contentControls.appendContent', 'contentControls.checkbox.getState', 'contentControls.checkbox.setState', 'contentControls.checkbox.setSymbolPair', 'contentControls.checkbox.toggle', 'contentControls.choiceList.getItems', 'contentControls.choiceList.setItems', 'contentControls.choiceList.setSelected', 'contentControls.clearBinding', 'contentControls.clearContent', 'contentControls.copy', 'contentControls.date.clearValue', 'contentControls.date.setCalendar', 'contentControls.date.setDisplayFormat', 'contentControls.date.setDisplayLocale', 'contentControls.date.setStorageFormat', 'contentControls.date.setValue', 'contentControls.delete', 'contentControls.get', 'contentControls.getBinding', 'contentControls.getContent', 'contentControls.getParent', 'contentControls.getRawProperties', 'contentControls.group.ungroup', 'contentControls.group.wrap', 'contentControls.insertAfter', 'contentControls.insertBefore', 'contentControls.list', 'contentControls.listChildren', 'contentControls.listInRange', 'contentControls.move', 'contentControls.normalizeTagPayload', 'contentControls.normalizeWordCompatibility', 'contentControls.patch', 'contentControls.patchRawProperties', 'contentControls.prependContent', 'contentControls.repeatingSection.cloneItem', 'contentControls.repeatingSection.deleteItem', 'contentControls.repeatingSection.insertItemAfter', 'contentControls.repeatingSection.insertItemBefore', 'contentControls.repeatingSection.listItems', 'contentControls.repeatingSection.setAllowInsertDelete', 'contentControls.replaceContent', 'contentControls.selectByTag', 'contentControls.selectByTitle', 'contentControls.setBinding', 'contentControls.setLockMode', 'contentControls.setType', 'contentControls.text.clearValue', 'contentControls.text.setMultiline', 'contentControls.text.setValue', 'contentControls.unwrap', 'contentControls.validateWordCompatibility', 'contentControls.wrap', 'create.contentControl'],
  'create': ['create.heading', 'create.image', 'create.paragraph', 'create.sectionBreak', 'create.table', 'create.tableOfContents'],
  'crossRefs': ['crossRefs.get', 'crossRefs.insert', 'crossRefs.list', 'crossRefs.rebuild', 'crossRefs.remove'],
  'customXml': ['customXml.parts.create', 'customXml.parts.list'],
  'fields': ['fields.get', 'fields.insert', 'fields.list', 'fields.rebuild', 'fields.remove'],
  'footnotes': ['footnotes.configure', 'footnotes.get', 'footnotes.insert', 'footnotes.list', 'footnotes.remove', 'footnotes.update'],
  'format': ['format.apply'],
  'format.paragraph': ['format.paragraph.clearAlignment', 'format.paragraph.clearAllTabStops', 'format.paragraph.clearBorder', 'format.paragraph.clearDirection', 'format.paragraph.clearIndentation', 'format.paragraph.clearShading', 'format.paragraph.clearSpacing', 'format.paragraph.clearTabStop', 'format.paragraph.resetDirectFormatting', 'format.paragraph.setAlignment', 'format.paragraph.setBorder', 'format.paragraph.setDirection', 'format.paragraph.setFlowOptions', 'format.paragraph.setIndentation', 'format.paragraph.setKeepOptions', 'format.paragraph.setOutlineLevel', 'format.paragraph.setShading', 'format.paragraph.setSpacing', 'format.paragraph.setTabStop'],
  'headerFooters': ['headerFooters.get', 'headerFooters.list', 'headerFooters.parts.create', 'headerFooters.parts.delete', 'headerFooters.parts.list', 'headerFooters.refs.clear', 'headerFooters.refs.set', 'headerFooters.refs.setLinkedToPrevious', 'headerFooters.resolve'],
  'history': ['history.get', 'history.redo', 'history.undo'],
  'hyperlinks': ['hyperlinks.get', 'hyperlinks.insert', 'hyperlinks.list', 'hyperlinks.patch', 'hyperlinks.remove', 'hyperlinks.wrap'],
  'images': ['images.convertToFloating', 'images.convertToInline', 'images.crop', 'images.delete', 'images.flip', 'images.get', 'images.insertCaption', 'images.list', 'images.move', 'images.removeCaption', 'images.replaceSource', 'images.resetCrop', 'images.rotate', 'images.scale', 'images.setAltText', 'images.setAnchorOptions', 'images.setDecorative', 'images.setHyperlink', 'images.setLockAspectRatio', 'images.setName', 'images.setPosition', 'images.setSize', 'images.setWrapDistances', 'images.setWrapSide', 'images.setWrapType', 'images.setZOrder', 'images.updateCaption'],
  'index': ['index.configure', 'index.entries.get', 'index.entries.insert', 'index.entries.list', 'index.entries.remove', 'index.entries.update', 'index.get', 'index.insert', 'index.list', 'index.rebuild', 'index.remove'],
  'lists': ['lists.applyPreset', 'lists.applyStyle', 'lists.applyTemplate', 'lists.attach', 'lists.canContinuePrevious', 'lists.canJoin', 'lists.captureTemplate', 'lists.clearLevelOverrides', 'lists.continuePrevious', 'lists.convertToText', 'lists.create', 'lists.detach', 'lists.get', 'lists.getStyle', 'lists.indent', 'lists.insert', 'lists.join', 'lists.list', 'lists.merge', 'lists.outdent', 'lists.restartAt', 'lists.separate', 'lists.setLevel', 'lists.setLevelAlignment', 'lists.setLevelBullet', 'lists.setLevelIndents', 'lists.setLevelLayout', 'lists.setLevelMarkerFont', 'lists.setLevelNumbering', 'lists.setLevelNumberStyle', 'lists.setLevelPictureBullet', 'lists.setLevelRestart', 'lists.setLevelStart', 'lists.setLevelText', 'lists.setLevelTrailingCharacter', 'lists.setType', 'lists.setValue', 'lists.split'],
  'metadata': ['metadata.get', 'metadata.list', 'metadata.remove', 'metadata.resolve', 'metadata.update'],
  'mutations': ['mutations.apply', 'mutations.preview'],
  'permissionRanges': ['permissionRanges.create', 'permissionRanges.get', 'permissionRanges.list', 'permissionRanges.remove', 'permissionRanges.updatePrincipal'],
  'protection': ['protection.clearEditingRestriction', 'protection.get', 'protection.setEditingRestriction'],
  'query': ['query.match'],
  'ranges': ['ranges.resolve'],
  'sections': ['sections.clearHeaderFooterRef', 'sections.clearPageBorders', 'sections.get', 'sections.list', 'sections.setBreakType', 'sections.setColumns', 'sections.setHeaderFooterMargins', 'sections.setHeaderFooterRef', 'sections.setLineNumbering', 'sections.setLinkToPrevious', 'sections.setOddEvenHeadersFooters', 'sections.setPageBorders', 'sections.setPageMargins', 'sections.setPageNumbering', 'sections.setPageSetup', 'sections.setSectionDirection', 'sections.setTitlePage', 'sections.setVerticalAlign'],
  'selection': ['selection.current'],
  'styles': ['styles.apply'],
  'styles.paragraph': ['styles.paragraph.clearStyle', 'styles.paragraph.setStyle'],
  'tables': ['tables.applyBorderPreset', 'tables.clearBorder', 'tables.clearCellSpacing', 'tables.clearContents', 'tables.clearDefaultStyle', 'tables.clearShading', 'tables.clearStyle', 'tables.convertFromText', 'tables.convertToText', 'tables.delete', 'tables.deleteCell', 'tables.deleteColumn', 'tables.deleteRow', 'tables.distributeColumns', 'tables.distributeRows', 'tables.get', 'tables.getCells', 'tables.getProperties', 'tables.getStyles', 'tables.insertCell', 'tables.insertColumn', 'tables.insertRow', 'tables.mergeCells', 'tables.move', 'tables.setAltText', 'tables.setBorder', 'tables.setBorders', 'tables.setCellPadding', 'tables.setCellSpacing', 'tables.setColumnWidth', 'tables.setDefaultStyle', 'tables.setLayout', 'tables.setRowHeight', 'tables.setRowOptions', 'tables.setShading', 'tables.setStyle', 'tables.setStyleOption', 'tables.setTableOptions', 'tables.setTablePadding', 'tables.sort', 'tables.split', 'tables.splitCell', 'tables.unmergeCells'],
  'toc': ['toc.configure', 'toc.editEntry', 'toc.get', 'toc.getEntry', 'toc.list', 'toc.listEntries', 'toc.markEntry', 'toc.remove', 'toc.unmarkEntry', 'toc.update'],
  'trackChanges': ['trackChanges.decide', 'trackChanges.get', 'trackChanges.list'],
};

